### ISSUE TITLE
Offset with string "px" not working

### ISSUE THREAD

**Issue by valentin-anamorphik** [russellgoldenberg/scrollama#114]
Hi,

I added an offset of 100px.

Debug mode show : `trigger: 0`
![2020-07-16_10h51_00](https://user-images.githubusercontent.com/32865180/87650647-41003600-c752-11ea-99b2-29100420a6d4.png)

```
// instantiate the scrollama
const scroller = scrollama();

// setup the instance, pass callback functions
scroller
  .setup({
    step: ".step",
    offset: "100px",
  })
  .onStepEnter(response => {
    // { element, index, direction }
  })
  .onStepExit(response => {
    // { element, index, direction }
  });

// setup resize event
window.addEventListener("resize", scroller.resize);
```

**Comment by russellgoldenberg** [comment]
the screenshot you attached doesn't have a class of "step", so not sure what the complete code looks like. I just tried a fresh example with 100px offset and worked on major browsers. So I think its just a class name problem? Otherwise if you could share an actual link to the issue or more complete source code that would be helpful.
