### ISSUE TITLE
Keyboard listeners

### ISSUE THREAD

**Issue by martgnz** [russellgoldenberg/scrollama#21]
Would be great to be able to navigate between steps using the keyboard arrows and the space bar.

[graph-scroll](https://github.com/1wheel/graph-scroll/blob/gh-pages/graph-scroll.js#L66) has it, and it's quite handy.

**Comment by russellgoldenberg** [comment]
I don't modify the default keyboard interaction, which still scrolls the page like normal and works fine. It looks like graph scroll hijacks the keyboard events and advances it like a slide. While it is doable, I would prefer to leave that choice up to the developer implementing it on their own, rather than as a default behavior of the library. Thanks for the input though.
