### ISSUE TITLE
onStepEnter and onStepExit fire in wrong order?

### ISSUE THREAD

**Issue by codeofsumit** [russellgoldenberg/scrollama#43]
Let's say I got 5 divs of a height of 500px each on a page.
If I scroll through it and log the Enter and Exit events when they go passed the offset treshold, the events are fired like this:

Enter (1st element enters)
Enter (2nd element enters)
Exit (1st element exits)
Enter (3rd element enters)
Exit (2nd Element exits)
...

What I would've expected:

Enter (1st element enters)
Exit (1st element exits)
Enter (2nd element enters)
Exit (2nd Element exits)
Enter (3rd element enters)
...

is there a specific reason for this order?

**Comment by codeofsumit** [comment]
The `progress` event also fires once after the steps `exit`.
I would've expected the `exit` event is the last one for that step?

**Comment by russellgoldenberg** [comment]
Just pushed a bunch of changes and a new release - preserving order is one of the updates. Let me know if we can close this issue. In regards to progress, that is because the progress won't hit 0 or 100% on its own, so the enter/exit triggers call another update to progress. I just peaked at code and it looks like I can simply change the order those are fired and it should be good to go. I'll open a new issue for that.

**Comment by codeofsumit** [comment]
uhhh this looks MUCH better. I was able to remove a lot of workaround-code now 👍
