### ISSUE TITLE
Option to only fire once

### ISSUE THREAD

**Issue by hendrikeng** [russellgoldenberg/scrollama#51]
Hey thanks for the really good work, its a lightweight modern alternative to scrollmagic that works really well with gsap/TweenMax and i am digging it so far :-)

Is there an option to disable trigger on reverse, like `reverse: false` or `loop: false` only saw the option to destroy/disable the controller

**Comment by russellgoldenberg** [comment]
By reverse to you mean scrolling up? Or specifically trigger the element once then stop watching for any changes, regardless of direction? The former can be handled in your own implementation, since the `onStepEnter` callback returns a `direction` property. Otherwise, I could add an option to remove the observer after a step is triggered.

**Comment by hendrikeng** [comment]
@russellgoldenberg i meant to remove the observer after a step is triggered, i think it would be very useful to have the option. Thanks a lot Russell
