### ISSUE TITLE
onStepProgress does not pass progress when resizing window

### ISSUE THREAD

**Issue by janwillemtulp** [russellgoldenberg/scrollama#65]
I have `progress` set to true, and when I resize the browser window, due to the changes in height of the steps, I notice that the `handleProgress` is executed. However, the `event.progress` is not set. 

It seems like if you resize your window, and the height of steps depends on viewport height, then the height of a step will change during browser window resize, and thus the progress during the step should also change then.

**Comment by russellgoldenberg** [comment]
Thanks I'll check it out. Just to be sure we are looking at the same thing, are you firing the [resize function](https://github.com/russellgoldenberg/scrollama#scrollamaresize) after the step heights change?

**Comment by janwillemtulp** [comment]
Yes, in the callback `onWindowResize` for `window.addEventListener('resize', debounce(onWindowResize, 350), false)`, the 'resize()' function on `scrollama` is the last thing I call in the callback. Before this, I change scale ranges, SVG width and height, etc.

**Comment by russellgoldenberg** [comment]
https://russellgoldenberg.github.io/scrollama/progress/

I logged out the results in the demo, and everything seems to be working as it should... except for 1 bug. Sometimes when the progress fires and and the step enters at the same time, it triggers 2 progress updates (intentional on my part), but the order is guaranteed.

This was a trade-off  - to make sure progress always hits 0 or 1 on enter/exit (which it won't on its own). Since intersectionObserver is async, the order isn't always the same... However, this is undesirable, so it might just make more sense to revert it, and the user may have to manually trigger progress 0 or 1 on enter/exit of steps if they need that exactness.

This might not make sense because it is more about how the library works internally, but if you are seeing something different let me know.

**Comment by russellgoldenberg** [comment]
fixed in v2

**Comment by giacomobg** [comment]
Heya, I think I'm having the same issue in 3.2.0.

It's happening intermittently both locally and in a CMS.

Not necessarily sure it's just connected to resizing, but I noticed that to start with `onStepProgress` passes progress just fine and then as soon as I resized the page it only passed steps. I have a `window.onresize()` line and it makes no difference whether or not I've commented it out, either way on resize it breaks.

I'm very very new to scrollama so sorry if I've missed any details, not sure how to check what's going on with it internally.
