### ISSUE TITLE
When refreshing the page, the wrong index might be triggered

### ISSUE THREAD

**Issue by jwhazel** [russellgoldenberg/scrollama#70]
OSX 10.12, replicated on both Firefox(60) and Chrome(67)

**Example:** https://russellgoldenberg.github.io/scrollama/sticky-js/ (or any of the other demos)
**Instructions:** scroll down past the first element (the further the better). Hit refresh a couple of times
**Expected behavior:** When page is refreshed, it should pass the correct index into the function handler so it properly detects which element you are intersecting
**Actual behavior:** it will occasionally show the index of one of the prior elements. See screenshot taken on Firefox (should be registering step 4). It seems like it could possibly be some sort of race condition.

I'm unclear if this bug is related to the core library itself or just the examples. I noticed it in one of my pages since I was using most of the example code as a template. Interestingly enough, I cannot replicate this on Safari(11).

![example_firefox_osx](https://user-images.githubusercontent.com/5685892/41619368-fc9d1966-73d3-11e8-893e-ee6942b9f015.jpeg)

**Comment by marcdepoe** [comment]
I've done a little digging and in my testing have found that when the page is refreshed at a point anywhere past the first step, a random step with an index less than or equal to the current step will be given (in the examples above) the `is-active` class.

The specific reason for this appears to be because of the nature of the implemented observer pattern and the fact that step order does indeed matter in this (refresh) case. I've only tested in Chrome and am unsure how much of a role browser plays.

See https://github.com/russellgoldenberg/scrollama/blob/master/src/init.js

`intersectViewportAbove()` is triggered for all steps preceding the active step, which in turn calls `notifyStepEnter()` for each of those steps. Then, the actual active step, and all steps preceding it, are applied the `is-active` class (or whatever your onStepEnter callback does) in a seemingly random order because of the asynchronous nature of the calls. So the `is-active` class ends up on whichever response/step is triggered last.

That said, this behavior can be hack-remedied by commenting out this call inside `updateIO()` - line 500 (642 of current 1.4.4 build file) as default direction is 'down':
```
// updateViewportAboveIO();
```
.. which binds `intersectViewportAbove`, and according to the comments is supposed to be a fallback anyway? I haven't noticed any unintended consequences but I'm just getting acquainted ¯\\\_(ツ)_/¯

So I'm not sure what an elegant solution looks like, but one _could_ also temporarily work around this until it's fixed by tracking both direction and index (min/max) in their stepEnter/stepProgress handler.

**Example:** <sup><sub>don't judge</sub></sup>
_based on https://russellgoldenberg.github.io/scrollama/fixed-js/_
```javascript
function handleStepEnter(response) {
  
  const lower_step_limit = 0;
  const upper_step_limit = Number.MAX_SAFE_INTEGER;

  const default_direction = 'down';
  const default_step_limit = lower_step_limit;

  this.direction = (typeof this.direction === 'undefined') ? default_direction : this.direction;
  this.step_limit = (typeof this.step_limit === 'undefined') ? default_step_limit : this.step_limit;
  this.active_flag = (this.direction === default_direction);

  if (this.direction !== response.direction) {
    this.direction = response.direction;
    this.step_limit = (this.active_flag = (this.direction === 'down')) ? lower_step_limit : upper_step_limit;
  }

  if ( (this.step_limit <= response.index) === this.active_flag) {
    this.step_limit = response.index;

    /*  <YOUR_EXISTING_CODE> */
    // response = { element, direction, index }

    // add color to current step only
    step.classed('is-active', function (d, i) {
      return i === response.index;
    })

    // update graphic based on step
    graphic.select('p').text(response.index + 1);
    /*  </YOUR_EXISTING_CODE> */
  }

}
```

HTH

**Comment by russellgoldenberg** [comment]
fixed in v2
